import seaborn as sns

bg_color = '0.10'
sns.set(font='Segoe UI',
        rc={'figure.figsize': (14,6),
            'figure.dpi': 120,
            'savefig.dpi': 300,
            'figure.facecolor': bg_color,
            'savefig.facecolor': bg_color,
            'axes.titlesize': 22,
            'axes.titleweight': 'bold',
            'axes.titlepad': 25,          
            'axes.labelsize': 16,
            'axes.labelsize': 16,
            'xtick.labelsize': 14,
            'ytick.labelsize': 14,
            'axes.spines.right': False,
            'axes.spines.top': False,
            'axes.spines.left': False,
            'axes.spines.bottom': False,
            'axes.edgecolor': 'dimgrey',
            'axes.facecolor': bg_color,
            'axes.labelcolor': 'white',
            'axes.grid.axis': 'y',
            'grid.color': 'dimgrey',
            'grid.linestyle': '--',
            'grid.linewidth': 0.75,
            'legend.facecolor': bg_color,
            'legend.edgecolor': 'none',
            'lines.linewidth': 1,
            'lines.solid_capstyle': 'round',
            'lines.dashed_pattern': (7, 5),
            'patch.edgecolor': 'w',
            'patch.force_edgecolor': True,
            'text.color': 'white',
            'xtick.bottom': True,
            'axes.labelcolor': 'white',
            'xtick.color': 'white',
            'xtick.direction': 'out',
            'xtick.top': False,
            'ytick.color': 'white',
            'ytick.direction': 'out',
            'ytick.left': False,
            'ytick.right': False})